Fix compilation of test.
This commit fix a series of errors about inclusion of windows' headers.
They are summarized here for completeness :

- fatal error C1189: #error:  "No Target Architecture"
  => need to include "windows.h" before

- error C2131: expression did not evaluate to a constant
  => Some includes before windows' header define something and break
     window's header compilation. The real solution would be to know
     what is defined. Other solution is to include window's header first.

- error C2220: warning treated as error - no 'object' file generated
  warning C4003: not enough arguments for function-like macro invocation 'min'
  => Some window's headers define min/max as macro.
     #undef min/max